defaultProject: wv63-virgiliojose
defaultLocation: US
defaultDataset: dataform
defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.0-beta.4
vars:
    date_of_interest: "CURRENT_DATE() - 1"
